package docs:calculator@0.1.0;

interface hi {
  use types.{btc-or-eth-wallet};

  variant player {
    alice(btc-or-eth-wallet),
    bob(btc-or-eth-wallet),
  } 
}

interface types {
  use docs:adder/api-types@0.1.0.{wallet};

  record btc-or-eth-wallet {
    w: wallet,
  }
}

world xml-hello {
  export hi;
  export types;
}
