package docs:adder@0.1.0;

interface api {
    use types.{balance};

    variant wallet {
        btc(balance),
        eth(balance),
    }

    incr: func(self: wallet, value: u64) -> result<wallet, string>;
}

interface types {
    record balance {
        value: u64,
    }
}

world docs-adder {
    export api;
}
